using System.Text.Json.Serialization;
using BinancePayDotnetSdk.Common.Enums;

namespace BinancePayDotnetSdk.Common.Models
{
    public class CreateOrderDataModel : ApiResponseDataModel
    {
        /// <summary>
        /// unique id generated by binance
        /// </summary>
        [JsonPropertyName("prepayId")]
        public string PrepayId { get; set; }
        /// <summary>
        /// operate entrance
        /// "WEB", "APP"
        /// </summary>
        [JsonPropertyName("tradeType")]
        [JsonConverter(typeof(JsonStringEnumConverter))]
        public TradeType TradeType { get; set; }
        /// <summary>
        /// expire time in milli seconds
        /// </summary>
        [JsonPropertyName("expireTime")] 
        public long ExpireTime { get; set; }
        /// <summary>
        /// qr code img link
        /// </summary>
        [JsonPropertyName("qrcodeLink")] 
        public string QrCodeLink { get; set; }
        /// <summary>
        /// qr contend info
        /// </summary>
        [JsonPropertyName("qrContent")]
        public string QrContent { get; set; }
    }
}