using System;
using System.Text.Json.Serialization;
using BinancePayDotnetSdk.Common.Converters;
using BinancePayDotnetSdk.Common.Enums;

namespace BinancePayDotnetSdk.Common.Models
{
    /// <summary>
    /// https://developers.binance.com/docs/binance-pay/api-order-create#child-attribute
    /// </summary>
    public class CreateOrderResponseDataModel
    {
        /// <summary>
        /// Unique id generated by binance.
        /// Letter or digit, no other symbol allowed.
        /// </summary>
        [JsonPropertyName("prepayId")]
        public string PrepayId { get; init; }
        
        /// <summary>
        /// Operate entrance.
        /// </summary>
        [JsonPropertyName("tradeType")]
        [JsonConverter(typeof(JsonStringEnumConverter))]
        public TradeType TradeType { get; init; }
        
        /// <summary>
        /// Expire time.
        /// </summary>
        [JsonPropertyName("expireTime")] 
        [JsonConverter(typeof(JsonMillisecondsDateTimeOffsetConverter))]
        public DateTimeOffset ExpireTime { get; init; }
        
        /// <summary>
        /// QrCode img link.
        /// </summary>
        [JsonPropertyName("qrcodeLink")] 
        public string QrCodeLink { get; init; }
        
        /// <summary>
        /// Qr content info.
        /// </summary>
        [JsonPropertyName("qrContent")]
        public string QrContent { get; init; }
    }
}