using System.Text.Json.Serialization;
using BinancePayDotnetSdk.Common.Converters;

namespace BinancePayDotnetSdk.Common.Models
{
    /// <summary>
    /// https://developers.binance.com/docs/binance-pay/api-submerchant-add#addsubmerchantresponse
    /// </summary>
    public class CreateSubMerchantResponseDataModel
    {
        /// <summary>
        /// Unique sub-merchant id generated by payment.
        /// </summary>
        [JsonPropertyName("subMerchantId")]
        [JsonConverter(typeof(JsonStringLongConverter))]
        public long SubMerchantId { get; init; }
    }
}