using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;
using BinancePayDotnetSdk.Common.Converters;
using BinancePayDotnetSdk.Common.Enums;

namespace BinancePayDotnetSdk.Common.Forms
{
    /// <summary>
    /// https://developers.binance.com/docs/binance-pay/api-wallet-transfer#request-parameters
    /// </summary>
    public class TransferFundForm : ApiRequestForm
    {
        /// <summary>
        /// Represents the unique ID of each transfer request.Generated by the merchant.
        /// </summary>
        [Required]
        [MaxLength(32)]
        [JsonPropertyName("requestId")]
        public string RequestId { get; set; }
        
        /// <summary>
        /// The merchant account id, issued when merchant been created at Binance.
        /// </summary>
        [Required]
        [JsonPropertyName("merchantId")]
        [JsonConverter(typeof(JsonStringLongConverter))]
        public long MerchantId { get; set; }

        [Required]
        [JsonPropertyName("currency")]
        public CurrencyType Currency { get; set; }
        
        /// <summary>
        /// Greater than 0.
        /// </summary>
        [Required]
        [JsonPropertyName("amount")]
        [JsonConverter(typeof(JsonStringDoubleConverter))]
        public double Amount { get; set; }
        
        /// <summary>
        /// The transfer direction specified by the merchant.
        /// </summary>
        [Required]
        [JsonPropertyName("transferType")] 
        [JsonConverter(typeof(JsonStringEnumConverter))]
        public TransferType TransferType { get; set; }
    }
}