using System.Text.Json.Serialization;
using BinancePayDotnetSdk.Common.Converters;
using BinancePayDotnetSdk.Common.Enums;

namespace BinancePayDotnetSdk.Common.Forms
{
    /// <summary>
    /// https://developers.binance.com/docs/binance-pay/api-wallet-transfer#request-parameters
    /// </summary>
    public class TransferFundForm : ApiMerchantRequestForm
    {
        /// <summary>
        /// Represents the unique ID of each transfer request.Generated by the merchant.
        /// maximum length 32
        /// </summary>
        [JsonPropertyName("requestId")]
        public string RequestId { get; set; }
        /// <summary>
        /// transfer currency, e.g. "BUSD"
        /// </summary>
        [JsonPropertyName("currency")]
        public CurrencyType Currency { get; set; }
        /// <summary>
        /// The transfer amount
        /// Greater than 0
        /// </summary>
        [JsonPropertyName("amount")]
        [JsonConverter(typeof(JsonStringDoubleConverter))]
        public double Amount { get; set; }
        /// <summary>
        /// The transfer direction specified by the merchant.
        /// </summary>
        [JsonPropertyName("transferType")] 
        [JsonConverter(typeof(JsonStringEnumConverter))]
        public TransferType TransferType { get; set; }
    }
}